   # NUMPY

***FIRST METHOD TO CREATE ARRAY***

In [1]:
import numpy as np

In [2]:
listarray=np.array([[3,43,4,43,44,3],[34,3,4,34,2,2]],np.int64)

In [3]:
listarray[1,1]

3

In [4]:
listarray.shape

(2, 6)

In [5]:
listarray.dtype

dtype('int64')

In [6]:
listarray.size

12

In [7]:
listarray[0,1]=30947

In [8]:
listarray

array([[    3, 30947,     4,    43,    44,     3],
       [   34,     3,     4,    34,     2,     2]], dtype=int64)

In [9]:
tupplearray=np.array((1,2,1,3,3))

In [10]:
tupplearray

array([1, 2, 1, 3, 3])

***SECOND METHOD TO CREATE ARRAY***

In [11]:
ZEROS=np.zeros((25))

In [12]:
ZEROS.reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
ARRANGE=np.arange(25)

In [14]:
ARRANGE

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
LINESPACE = np.linspace(1,25,15)

In [16]:
LINESPACE

array([ 1.        ,  2.71428571,  4.42857143,  6.14285714,  7.85714286,
        9.57142857, 11.28571429, 13.        , 14.71428571, 16.42857143,
       18.14285714, 19.85714286, 21.57142857, 23.28571429, 25.        ])

In [17]:
EMPTYARRAY=np.empty((2,4))

In [18]:
EMPTYARRAY

array([[6.23042070e-307, 1.42417221e-306, 1.37961641e-306,
        1.11261027e-306],
       [1.11261502e-306, 1.42410839e-306, 7.56597770e-307,
        2.44032786e-312]])

In [19]:
IDENTITYARRAY=np.identity(10)

In [20]:
IDENTITYARRAY

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
IDENTITYARRAY.reshape((50,2))

array([[1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.]])

In [23]:
IDENTITYARRAY.ravel() #MAKEONEDARRAY

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [24]:
ARRAY = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
ARRAY

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
ARRAY.sum(axis=0)

array([12, 15, 18])

In [28]:
ARRAY.sum(axis=1)

array([ 6, 15, 24])

In [29]:
TRANSPOSARRAY = ARRAY.T

In [30]:
TRANSPOSARRAY

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
for FLAT in ARRAY.flat:
    print(FLAT)

1
2
3
4
5
6
7
8
9


In [32]:
NEWARRAY=np.array([45,34,5,3453,5,34,5,3])

In [33]:
NEWARRAY.argmax()#return index

3

In [34]:
NEWARRAY.argmin()#return index

7

In [35]:
NEWARRAY.argsort()#return index

array([7, 2, 4, 6, 1, 5, 0, 3], dtype=int32)

In [36]:
ARRAY

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
ARRAY.argmin()

0

In [41]:
ARRAY.argmax()

8

In [42]:
ARRAY.argmin(axis=0)

array([0, 0, 0], dtype=int32)

In [43]:
ARRAY.argmax(axis=0)

array([2, 2, 2], dtype=int32)

In [44]:
ARRAY.argmin(axis=1)

array([0, 0, 0], dtype=int32)

In [45]:
ARRAY.argmax(axis=1)

array([2, 2, 2], dtype=int32)

In [46]:
ARRAY.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int32)

In [47]:
ARRAY.argmax(axis=1)

array([2, 2, 2], dtype=int32)

In [48]:
ARRAY2=np.array([[9,8,7],[6,5,4],[3,2,1]])

In [49]:
ARRAY

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
ARRAY2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [51]:
ARRAY2+ARRAY

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [52]:
ARRAY2*ARRAY

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [53]:
np.sqrt(ARRAY)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

(array([2, 2, 2], dtype=int32), array([0, 1, 2], dtype=int32))