# Numpy Practice with Problem

Print Numpy version and configuration information.

In [1]:
import numpy as np
print(np.__version__,np.show_config(),end="\n")

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
1.19.2 None


Create a numpy array with numbers ranging from 50 to 100.Also print attributes of
created object.

In [2]:
ARR_50_100=np.arange(50,101)
ARR_50_100

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

Create a null vector of size 10.

In [3]:
NULL_VECTOR=np.zeros(10)
NULL_VECTOR

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create a vector of size 10 initialized with random integers with a seed equal to last four
digits of your enrollment number.

In [22]:
import random 
random.seed(7018)#for getting same number of sequence like username or password first it random but after it not ..
SEED_ARRAY=np.array([np.random.randint(10) for i in range(10)])
SEED_ARRAY

array([0, 1, 1, 1, 7, 0, 4, 4, 9, 5])

Create a matrix of size 5x5 initialized with random integers with a seed equal to last four
digits of your enrollment number.

In [24]:
matrix=np.array([[np.random.randint(10) for i in range(5)]for i in range(5)])
matrix

array([[6, 4, 6, 4, 9],
       [1, 5, 4, 0, 8],
       [6, 8, 6, 4, 1],
       [2, 4, 7, 7, 3],
       [3, 8, 1, 3, 8]])

Create an identity matrix of size 5x5.

In [25]:
IDENTITY=np.identity(5)
IDENTITY

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Create a numpy array mat1 of size 5x2 with numbers ranging from 1 to 10.

In [26]:
mat1=np.arange(1,11)
new_mat1=mat1.reshape(5,2)
new_mat1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

Create another numpy array mat2 of size 2x5 with floating point numbers
between 10 to 20.

In [27]:
mat2=np.arange(10,20,dtype="float")
new_mat2=mat2.reshape(2,5)
new_mat2

array([[10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

Calculate the matrix product of mat1 and mat2.

In [28]:
product=new_mat1.dot(new_mat2)
product

array([[ 40.,  43.,  46.,  49.,  52.],
       [ 90.,  97., 104., 111., 118.],
       [140., 151., 162., 173., 184.],
       [190., 205., 220., 235., 250.],
       [240., 259., 278., 297., 316.]])

Print vector containing minimum and maximum in each row of mat1.

In [29]:
min=new_mat1.min(axis=1)
max=new_mat1.max(axis=1)
print(min,max,sep="\n")

[1 3 5 7 9]
[ 2  4  6  8 10]


Print vector containing mean and standard deviation in each column of mat2.

In [30]:
mean=new_mat2.mean(axis=0)
std=new_mat2.std(axis=0)
print(mean,std,sep="\n")

[12.5 13.5 14.5 15.5 16.5]
[2.5 2.5 2.5 2.5 2.5]


Perform vstack and hstack on mat1 and mat2.

In [31]:
vmat=np.vstack((mat1,mat2))
hmat=np.hstack((mat1,mat2))
print("vstack",vmat,"hstack",hmat,sep="\n")

vstack
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
hstack
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


Split mat1 horizontal into 2 and split mat2 vertical into 2 parts.

In [32]:
h=np.hsplit(new_mat1,2)
v=np.vsplit(new_mat2,2)
print(h,v,sep="\n")

[array([[1],
       [3],
       [5],
       [7],
       [9]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])]
[array([[10., 11., 12., 13., 14.]]), array([[15., 16., 17., 18., 19.]])]


Create a vector vec of size 20 initialized with double numbers ranging from 20 to 40 and
do the following.

In [33]:
mat=np.arange(20,40,dtype="double")
mat

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
       33., 34., 35., 36., 37., 38., 39.])

Reshape it to a 5x4 matrix mat.

In [34]:
new_mat=mat.reshape(5,4)
new_mat

array([[20., 21., 22., 23.],
       [24., 25., 26., 27.],
       [28., 29., 30., 31.],
       [32., 33., 34., 35.],
       [36., 37., 38., 39.]])

Print every 4th element of vec.

In [35]:
new_mat[:][4] #or mat[4][:]

array([36., 37., 38., 39.])

Print elements of vec less than or equal to 25.

In [36]:
for i in range(len(new_mat)):
    for j in range(len(new_mat[0])):
            if new_mat[i][j]>=25:
               print(new_mat[i][j])

25.0
26.0
27.0
28.0
29.0
30.0
31.0
32.0
33.0
34.0
35.0
36.0
37.0
38.0
39.0


In vec assign every number at even location to 1.

In [37]:
for j in range(len(new_mat)):
    for i in range(len(new_mat[0])):
        if new_mat[j][i]%2==0:
            new_mat[j][i]=1
new_mat

array([[ 1., 21.,  1., 23.],
       [ 1., 25.,  1., 27.],
       [ 1., 29.,  1., 31.],
       [ 1., 33.,  1., 35.],
       [ 1., 37.,  1., 39.]])

In vec assign from start position to 10th position every second element to 0.Reverse elements of vec.

In [38]:
mat[:10:2]=0
print(mat)
rev=mat[::-1]
print(rev)

[ 0. 21.  0. 23.  0. 25.  0. 27.  0. 29.  1. 31.  1. 33.  1. 35.  1. 37.
  1. 39.]
[39.  1. 37.  1. 35.  1. 33.  1. 31.  1. 29.  0. 27.  0. 25.  0. 23.  0.
 21.  0.]


In mat print each row in the second column and print each column in the second
row.

In [39]:
print(new_mat[0:5][1])
for i in range(5):
    print(new_mat[i][1])

[ 0. 25.  0. 27.]
21.0
25.0
29.0
33.0
37.0


Apply some universal functions such as sin,sqrt,cos,exp on vec.

In [40]:
radian=np.deg2rad(mat)
print(radian)
print("sin:",np.sin(radian))
print("cos:",np.cos(radian))
print("sqrt","\n",np.sqrt(mat))
print("exp:",np.exp(mat))

[0.         0.36651914 0.         0.40142573 0.         0.43633231
 0.         0.4712389  0.         0.50614548 0.01745329 0.54105207
 0.01745329 0.57595865 0.01745329 0.61086524 0.01745329 0.64577182
 0.01745329 0.68067841]
sin: [0.         0.35836795 0.         0.39073113 0.         0.42261826
 0.         0.4539905  0.         0.48480962 0.01745241 0.51503807
 0.01745241 0.54463904 0.01745241 0.57357644 0.01745241 0.60181502
 0.01745241 0.62932039]
cos: [1.         0.93358043 1.         0.92050485 1.         0.90630779
 1.         0.89100652 1.         0.87461971 0.9998477  0.8571673
 0.9998477  0.83867057 0.9998477  0.81915204 0.9998477  0.79863551
 0.9998477  0.77714596]
sqrt 
 [0.         4.58257569 0.         4.79583152 0.         5.
 0.         5.19615242 0.         5.38516481 1.         5.56776436
 1.         5.74456265 1.         5.91607978 1.         6.08276253
 1.         6.244998  ]
exp: [1.00000000e+00 1.31881573e+09 1.00000000e+00 9.74480345e+09
 1.00000000e+00 7.20048993

Print transpose and inverse of mat.

In [41]:
t=mat.transpose()
print(t)
# here somehow matrix inverse does not work in this matrix it has to be square so we take another matrix for that
inv_mat=np.arange(16,32,dtype="int")
nn=inv_mat.reshape(4,4)
inverse=np.linalg.inv(nn)
print(inverse)

[ 0. 21.  0. 23.  0. 25.  0. 27.  0. 29.  1. 31.  1. 33.  1. 35.  1. 37.
  1. 39.]
[[ 3.67352440e+14 -4.45061610e+14 -2.11934100e+14  2.89643270e+14]
 [-9.67832391e+14  1.34578154e+15  2.11934100e+14 -5.89883245e+14]
 [ 8.33607460e+14 -1.35637824e+15  2.11934100e+14  3.10836680e+14]
 [-2.33127510e+14  4.55658315e+14 -2.11934100e+14 -1.05967050e+13]]


# Demonstrate shallow copy and deep copy.

copy in Python (Deep Copy and Shallow Copy)
Last Updated: 10-02-2020
In Python, Assignment statements do not copy objects, they create bindings between a target and an object. When we use = operator user thinks that this creates a new object; well, it doesn’t. It only creates a new variable that shares the reference of the original object. Sometimes a user wants to work with mutable objects, in order to do that user looks for a way to create “real copies” or “clones” of these objects. Or, sometimes a user wants copies that user can modify without automatically modifying the original at the same time, in order to do that we create copies of objects.

A copy is sometimes needed so one can change one copy without changing the other. In Python, there are two ways to create copies :

Deep copy
Shallow copy
In order to make these copy, we use copy module. We use copy module for shallow and deep copy operations. For Example

In [42]:
import copy 
  
li1 = [1, 2, [3,5], 4] 
  
  
li2 = copy.copy(li1)  
  
li3 = copy.deepcopy(li1)  

print(li1)

[1, 2, [3, 5], 4]


In the above code, the copy() returns a shallow copy of list and deepcopy() return a deep copy of list.

Deep copy is a process in which the copying process occurs recursively. It means first constructing a new collection object and then recursively populating it with copies of the child objects found in the original. In case of deep copy, a copy of object is copied in other object. It means that any changes made to a copy of object do not reflect in the original object. In python, this is implemented using “deepcopy()” function.

In [44]:
import copy 
  
li1 = [1, 2, [3,5], 4] 
  
li2 = copy.deepcopy(li1) 
  
print ("The original elements before deep copying") 
for i in range(0,len(li1)): 
    print (li1[i],end=" ") 
  
print("\r") 
  
li2[2][0] = 7
  
print ("The new list of elements after deep copying ") 
for i in range(0,len( li1)): 
    print (li2[i],end=" ") 
  
print("\r") 
  
print ("The original elements after deep copying") 
for i in range(0,len( li1)): 
    print (li1[i],end=" ") 

The original elements before deep copying
1 2 [3, 5] 4 
The new list of elements after deep copying 
1 2 [7, 5] 4 
The original elements after deep copying
1 2 [7, 5] 4 

Important Points:
The difference between shallow and deep copying is only relevant for compound objects (objects that contain other objects, like lists or class instances):

A shallow copy constructs a new compound object and then (to the extent possible) inserts references into it to the objects found in the original.
A deep copy constructs a new compound object and then, recursively, inserts copies into it of the objects found in the original.